FROM debian:sid AS compile

ARG TARGETARCH

RUN apt-get update
RUN apt-get install --no-install-recommends -y libbpf-dev linux-headers-generic golang ca-certificates llvm-22 clang-22

RUN update-alternatives --install /usr/bin/clang clang $(which clang-22) 1
RUN update-alternatives --install /usr/bin/llvm-strip llvm-strip $(which llvm-strip-22) 1

WORKDIR /work
COPY go.mod go.sum ./
RUN --mount=type=cache,dst=/go/pkg/mod \
  go mod download

