// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package dummyxdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDummy returns the embedded CollectionSpec for dummy.
func loadDummy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DummyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dummy: %w", err)
	}

	return spec, err
}

// loadDummyObjects loads dummy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dummyObjects
//	*dummyPrograms
//	*dummyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDummyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDummy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dummySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dummySpecs struct {
	dummyProgramSpecs
	dummyMapSpecs
	dummyVariableSpecs
}

// dummyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dummyProgramSpecs struct {
	Dummy *ebpf.ProgramSpec `ebpf:"dummy"`
}

// dummyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dummyMapSpecs struct {
}

// dummyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dummyVariableSpecs struct {
}

// dummyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDummyObjects or ebpf.CollectionSpec.LoadAndAssign.
type dummyObjects struct {
	dummyPrograms
	dummyMaps
	dummyVariables
}

func (o *dummyObjects) Close() error {
	return _DummyClose(
		&o.dummyPrograms,
		&o.dummyMaps,
	)
}

// dummyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDummyObjects or ebpf.CollectionSpec.LoadAndAssign.
type dummyMaps struct {
}

func (m *dummyMaps) Close() error {
	return _DummyClose()
}

// dummyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDummyObjects or ebpf.CollectionSpec.LoadAndAssign.
type dummyVariables struct {
}

// dummyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDummyObjects or ebpf.CollectionSpec.LoadAndAssign.
type dummyPrograms struct {
	Dummy *ebpf.Program `ebpf:"dummy"`
}

func (p *dummyPrograms) Close() error {
	return _DummyClose(
		p.Dummy,
	)
}

func _DummyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dummy_bpfeb.o
var _DummyBytes []byte
