// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lbBackend struct {
	_    structs.HostLayout
	Ip   lbInAddr
	Port uint16
	Pad  [2]uint8
}

type lbConntrackEntry struct {
	_       structs.HostLayout
	SrcIp   lbInAddr
	DstIp   lbInAddr
	SrcPort uint16
	DstPort uint16
}

type lbFiveTupleT struct {
	_        structs.HostLayout
	SrcIp    lbInAddr
	DstIp    lbInAddr
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type lbInAddr struct {
	_      structs.HostLayout
	S_addr uint32
}

type lbLbAlgorithm uint32

const (
	lbLbAlgorithmRANDOM lbLbAlgorithm = 1
	lbLbAlgorithmHASH   lbLbAlgorithm = 2
)

type lbListenerEntry struct {
	_        structs.HostLayout
	Ip       lbInAddr
	Port     uint16
	Protocol uint8
	Pad      [1]uint8
}

// loadLb returns the embedded CollectionSpec for lb.
func loadLb() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LbBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lb: %w", err)
	}

	return spec, err
}

// loadLbObjects loads lb and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lbObjects
//	*lbPrograms
//	*lbMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLbObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLb()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lbSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbSpecs struct {
	lbProgramSpecs
	lbMapSpecs
	lbVariableSpecs
}

// lbProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbProgramSpecs struct {
	LoadBalance *ebpf.ProgramSpec `ebpf:"load_balance"`
}

// lbMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbMapSpecs struct {
	Conntrack   *ebpf.MapSpec `ebpf:"conntrack"`
	ListenerMap *ebpf.MapSpec `ebpf:"listener_map"`
	NumBackends *ebpf.MapSpec `ebpf:"num_backends"`
}

// lbVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbVariableSpecs struct {
	LbAlgo *ebpf.VariableSpec `ebpf:"lb_algo"`
}

// lbObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbObjects struct {
	lbPrograms
	lbMaps
	lbVariables
}

func (o *lbObjects) Close() error {
	return _LbClose(
		&o.lbPrograms,
		&o.lbMaps,
	)
}

// lbMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbMaps struct {
	Conntrack   *ebpf.Map `ebpf:"conntrack"`
	ListenerMap *ebpf.Map `ebpf:"listener_map"`
	NumBackends *ebpf.Map `ebpf:"num_backends"`
}

func (m *lbMaps) Close() error {
	return _LbClose(
		m.Conntrack,
		m.ListenerMap,
		m.NumBackends,
	)
}

// lbVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbVariables struct {
	LbAlgo *ebpf.Variable `ebpf:"lb_algo"`
}

// lbPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbPrograms struct {
	LoadBalance *ebpf.Program `ebpf:"load_balance"`
}

func (p *lbPrograms) Close() error {
	return _LbClose(
		p.LoadBalance,
	)
}

func _LbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lb_bpfeb.o
var _LbBytes []byte
