name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    name: Run E2E Tests 
    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-26.04]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true  

      - name: Download dependencies
        run: go mod download

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run E2E Tests
        run: gotestsum --junitfile test-results.xml -- -exec "sudo" -v ./test/e2e/...

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "test-results.xml"
          comment_mode: off
          check_run: false

      - name: Publish Verifier error logs as artifacts
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: verifier-log
          path: /tmp/verifier-*.log
          if-no-files-found: ignore
          archive: false
